FROM python:3.9

ENV POLYGRAPHY_AUTOINSTALL_DEPS=1
RUN python -m pip install --upgrade pip --no-cache-dir 
RUN python -m pip install colored polygraphy==0.47.1 --extra-index-url https://pypi.ngc.nvidia.com --no-cache-dir 

CMD []
