# If you are running on Mac M1/M2 you should use this Dockerfile to build a CPU-only image.
FROM python:3.9

RUN python -m pip install --upgrade pip --no-cache-dir
RUN python -m pip install transformers==4.29.2 --no-cache-dir
RUN python -m pip install optimum==1.8.5 --no-cache-dir
RUN python -m pip install optimum[onnxruntime]==1.8.5 --no-cache-dir

CMD []
