FROM python:3.9

RUN python -m pip install --upgrade pip
RUN python -m pip install numpy
RUN python -m pip install openvino-dev==2022.3.0
RUN python -m pip install  openvino-dev[onnx]==2022.3.0

CMD []



