{
 "title": "HuggingBench Main Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Client infer latency  p90",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le, batch_size, model) (rate(client_infer_latency_bucket[1m])))"
    }
   ]
  },
  {
   "title": "CPU used memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "nv_cpu_memory_used_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total CPU utlilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "nv_cpu_utilization*100", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Inference rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    { "expr": "rate(nv_inference_count[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Inference request duration (avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(nv_inference_request_duration_us[1m])/(rate(nv_inference_request_success[1m])+rate(nv_inference_request_failure[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}