global:
  scrape_interval: 5s # Benchmark runs are short lived, so we want to scrape frequently.
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'triton'
    static_configs:
      - targets: ['host.docker.internal:8002', 'docker.host:8002'] # triton server metric (one host when runnig o Mac other for Linux - this is a hack)

  - job_name: 'huggingbench'
    static_configs:
      - targets: ['host.docker.internal:8011', 'docker.host:8011'] # huggingbench metric

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['host.docker.internal:9100', 'docker.host:9100'] # node exporter metric

