# This image has problems working with Apple M1/M2 chips.
FROM python:3.10

RUN python -m pip install --upgrade pip --no-cache-dir 
RUN python -m pip install numpy --no-cache-dir 
RUN python -m pip install openvino-dev==2023.0.1 --no-cache-dir 

CMD []



