FROM python:3.9

RUN python -m pip install --upgrade pip
RUN python -m pip install numpy
RUN python -m pip install openvino-dev==2023.0.0.dev20230427
RUN python -m pip install openvino-dev==2023.0.0.dev20230427

CMD []



