name: HuggingBench

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - uses: psf/black@stable
    - name: Build Optimum Docker image
      run: cd docker && docker build -t optimum -f optimum/Dockerfile.cpu optimum/ 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install colored polygraphy==0.47.1 --extra-index-url https://pypi.ngc.nvidia.com
        python -m pip install .
    - name: Pull custom build Triton server image
      run: docker pull ghcr.io/niksajakovljevic/tritonserver:23.04-onnx
    - name: Test with pytest
      run: |
        python -m pip install pytest
        EXPERIMENT_RUN_INTERVAL=10 pytest --log-cli-level=INFO
